server:
  port: '9091'
  servlet:
    context-path: '/api/ms2/v1'
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/ms2'
    username: 'postgres'
    password: '123'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: 'ms2'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9093/eureka